spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/springdata
    username: yooguy
    password: 1234


  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate.format_sql: true

logging:
  level:
    org.hibernate.type.descriptor.sql: trace
